pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Deliver') {
            steps {
                sh 'mvn clean package -DskipTests dockerfile:build dockerfile:tag dockerfile:push'
            }
        }
    }
}